version: '3.0'
services:
    web:
        image: chrch/docker-pets:1.0
        ports:
            - '80:5000'
        networks:
            - pets-overlay
        environment:
            DB: db
        deploy:
            mode: replicated
            replicas: 2
    db:
        image: consul
        networks:
            - pets-overlay
networks:
    pets-overlay:
